# Generated by Django 3.2.9 on 2021-12-01 17:00

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('textual_paragraph', models.CharField(default='', max_length=9000)),
                ('author', models.CharField(default='', max_length=900)),
                ('date', models.DateField(default='2021-01-01')),
            ],
        ),
    ]
