# Generated by Django 3.2.9 on 2021-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
